"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var empleado_js_1 = require("./empleado.js");
var persona_js_1 = require("./persona.js");
var personaservicio_js_1 = require("./personaservicio.js");
var estudiante_js_1 = require("./estudiante.js");
var profesor_js_1 = require("./profesor.js");
var persona = new persona_js_1.Persona("Alex", "Aragundi", "1316065661", "Soltero");
persona.cambiarEstadoCivil("soltero");
var empleado = new empleado_js_1.Empleado("Alex", "Aragundi", "1316065661", "Soltero", 2016, 4656);
empleado.despacho(7777);
var estudiante = new estudiante_js_1.Estudiante("Alex", "Aragundi", "1316065661", "Soltero", "tercero", "tres");
estudiante.nuevaMatricula("cuatro");
var personaservicio = new personaservicio_js_1.PersonaServicio("Alex", "Aragundi", "1316065661", "Soltero", 2016, 4656, "cuatro");
personaservicio.trasladoSeccion("seis");
var profesor = new profesor_js_1.Profesor("Alex", "Aragundi", "1316065661", "Soltero", 2016, 4656, "fisica");
profesor.cambioCurso("ensamblaje");
console.log(persona);
console.log(empleado);
console.log(estudiante);
console.log(personaservicio);
console.log(profesor);
